vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodACL
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodACL2
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodAD1
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodAD2
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodAD5
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodALS
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodAMP2
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodAQS
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodBLE
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodBT2
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodCAN
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodCLS
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodCMPS2
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodCOLOR
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodDA1
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodDA4
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodDHB1
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodDPG1
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodENC
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodESP32
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodGPIO
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodGPS
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodGYRO
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodHYGRO
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodJSTK2
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodKYPD
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodMAXSONAR
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodMTDS
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodNAV
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodOLED
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodOLEDrgb
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodPIR
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodR2R
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodRTCC
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodSD
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodSF3
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodTC1
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodTMP3
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodToF
vivado -mode batch -source create_xsa.tcl -tclargs -block -jobs 12 PmodWIFI